[build]
  publish = "public"  # Remplacez "public" par le répertoire où vos fichiers statiques sont situés, si nécessaire
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
